image_dir: ./data/images/train
annotation_file: ./data/annotations.json
output_dir: ./data/output_annotated

# Optional
draw_labels: true
thickness: 2
font_scale: 0.6
alpha: 0.3  # 30% opacity for filled boxes